mutation AcceptInvestorInvitation($acceptInvestorInvitationInput: AcceptInvestorInvitationInput!) {
  acceptInvestorInvitation(acceptInvestorInvitationInput: $acceptInvestorInvitationInput) {
    ...InvestorBaseFragment
  }
}
