mutation InviteInvestor($invitationInput: CreateInvitationInput!) {
  inviteInvestor(invitationInput: $invitationInput) {
    id
    email
    invitation_code
    status
    type
    sent_at
    updated_at
  }
}

mutation UpdateInvestor($updateInvestorInput: UpdateInvestorInput!) {
  updateInvestor(updateInvestorInput: $updateInvestorInput) {
    ...InvestorAllFragment
  }
}

mutation CreateBankAccount($createBankAccountInput: CreateBankAccountInput!) {
  createBankAccount(createBankAccountInput: $createBankAccountInput) {
    ...BankAccountAllFragment
  }
}

mutation UpdateBankAccount($updateBankAccountInput: UpdateBankAccountInput!) {
  updateBankAccount(updateBankAccountInput: $updateBankAccountInput) {
    ...BankAccountAllFragment
  }
}

mutation AddInvestment($addInvestmentInput: AddInvestmentInput!) {
  addInvestment(addInvestmentInput: $addInvestmentInput) {
    id
    name
    balance
    created_at
    updated_at
  }
}

mutation Withdrawal($withdrawalInput: WithdrawalInput!) {
  withdrawal(withdrawalInput: $withdrawalInput) {
    ...TransactionsAllFragment
  }
}

mutation DeleteInvitation($id: Int!) {
  removeInvitation(id: $id) {
    ...InvitationBaseFragment
  }
}
