query RetrieveInvestor($id: Int!) {
  investor(id: $id) {
    bank_accounts {
      id
      account_number
      bank_name
      bank_country
      currency
      is_primary
    }
    ...InvestorAllFragment
  }
}

query ListInvestors {
  investors {
    ...InvestorAllFragment
  }
}

query ListInvitations(
  $emails: [String!]
  $status: InvitationStatus
  $statuses: [InvitationStatus!]
) {
  invitations(emails: $emails, status: $status, statuses: $statuses) {
    ...InvitationBaseFragment
  }
}
