query ListUsers($limit: Int, $page: Int) {
  users(limit: $limit, page: $page) {
    data {
      id
      middle_name
      avatar
      mobile_number
      last_name
      role
      email
      created_at
      updated_at
    }
  }
}
