mutation Login($loginInput: LoginInput!) {
  investorLogin(loginInput: $loginInput) {
    id
    first_name
    last_name
    email
    company_name
    is_accredited
    mobile_number
    account_status
    created_at
  }
}

mutation RequestPasswordReset(
  $requestPasswordResetInput: RequestPasswordResetInput!
) {
  requestPasswordReset(requestPasswordResetInput: $requestPasswordResetInput) {
    id
    first_name
    last_name
    type
    email
  }
}

mutation RestPassword($resetPasswordInput: ResetPasswordInput!) {
  resetPassword(resetPasswordInput: $resetPasswordInput) {
    id
    type
    first_name
    last_name
    email
  }
}

mutation ValidatePasswordResetToken(
  $validatePasswordResetTokenInput: ValidatePasswordResetTokenInput!
) {
  validatePasswordResetToken(
    validatePasswordResetTokenInput: $validatePasswordResetTokenInput
  ) {
    expiration_date
  }
}

mutation Logout {
  logout {
    status
  }
}
