mutation Login($loginInput: LoginInput!) {
  investorLogin(loginInput: $loginInput) {
    id
    first_name
    last_name
    email
    company_name
    is_accredited
    mobile_number
    account_status
    created_at
  }
}

mutation Logout {
  logout {
    status
  }
}
