export enum InvitationEvent {
  INVITATION_CREATED = 'INVITATION_CREATED',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  INVITATION_REJECTED = 'INVITATION_REJECTED',
  INVITATION_DELETED = 'INVITATION_DELETED',
}
