mutation Login($loginInput: LoginInput!) {
  login(loginInput: $loginInput) {
    id
    middle_name
    avatar
    mobile_number
    role
    first_name
    last_name
    email
    created_at
    updated_at
  }
}

mutation Logout {
  logout {
    status
  }
}
