mutation Login($loginInput: LoginInput!) {
  adminLogin(loginInput: $loginInput) {
    id
    middle_name
    avatar
    mobile_number
    role
    first_name
    last_name
    email
    created_at
    updated_at
  }
}

mutation RequestPasswordReset(
  $requestPasswordResetInput: RequestPasswordResetInput!
) {
  requestPasswordReset(requestPasswordResetInput: $requestPasswordResetInput) {
    id
    first_name
    last_name
    type
    email
  }
}

mutation RestPassword($resetPasswordInput: ResetPasswordInput!) {
  resetPassword(resetPasswordInput: $resetPasswordInput) {
    id
    type
    first_name
    last_name
    email
  }
}

mutation ValidatePasswordResetToken(
  $validatePasswordResetTokenInput: ValidatePasswordResetTokenInput!
) {
  validatePasswordResetToken(
    validatePasswordResetTokenInput: $validatePasswordResetTokenInput
  ) {
    expiration_date
  }
}

mutation Logout {
  logout {
    status
  }
}
