import { Box, Typography } from '@mui/material';
import CustomDataGrid from '../components/StyledDataGrid/CustomDataGrid';
import { useCreateCoolInvestorMutation, useListTestInvestorsQuery, useListUsersQuery, useRetrieveInvestorQuery } from '../lib/gql/gql-client';
import { useQueryClient } from '@tanstack/react-query';

const Index = () => {
  // Note: the `useListUsersQuery` hook is auto-generated by GraphQL Codegen.
  // The useListUsersQuery hook specifically comes from the .gql files located in
  // /lib/api/users.query.gql
  const users = useListUsersQuery(
    { limit: 100 },
    { select: (res) => res.users?.data }
  );

  return (
    <>
      <Box height={'100%'} m="2rem">
        <Typography variant="h4">Example table</Typography>
        <Typography variant="body2" mb={2}>
          Simple example on how to fetch data from the GraphQL API
        </Typography>

        <CustomDataGrid
          rows={users.data || []}
          loading={users.isLoading}
          columns={[
            {
              field: 'id',
              headerName: 'ID',
            },
            {
              field: 'name',
              valueGetter: (params) =>
                `${params.row.first_name} ${params.row.last_name}`,
            },
            {
              field: 'email',
            },
            {
              field: 'role',
            },
          ]}
        />
      </Box>
    </>
  );
};

export default Index;
