export const bankAccountTypes = [
  'Checking Account',
  'Savings Account',
  'Certificate of Deposit (CD)',
  'Money Market Account',
  'Joint Account',
  'Individual Retirement Account (IRA)',
  'Business Account',
  'Student Account',
  'High-Yield Savings Account',
  'Health Savings Account (HSA)',
  'Flexible Spending Account (FSA)',
  'Retirement Savings Account',
  'Custodial Account',
  'Brokerage Account',
  'Money Market Fund Account',
  'Online Savings Account',
  'Specialty Savings Account',
  'Corporate Account',
  'Non-Profit Organization Account',
  'Government Account',
  'Escrow Account',
  'Offshore Bank Account',
  'Islamic Banking Account',
];
